export const EU = new Set([
  'AT',
  'BE',
  'BG',
  'HR',
  'CY',
  'CZ',
  'DK',
  'EE',
  'FI',
  'FR',
  'DE',
  'GR',
  'HU',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MT',
  'NL',
  'PL',
  'PT',
  'RO',
  'SK',
  'SI',
  'ES',
  'SE']);

export const CountryToISO2 = [
  {
    countryNameEn: 'Andorra',
    countryCode: 'AD',
    region: 'Europe',
    flag: '🇦🇩',
  },
  {
    countryNameEn: 'Afghanistan',
    countryCode: 'AF',
    region: 'Asia & Pacific',
    flag: '🇦🇫',
  },
  {
    countryNameEn: 'Antigua and Barbuda',
    countryCode: 'AG',
    region: 'South/Latin America',
    flag: '🇦🇬',
  },
  {
    countryNameEn: 'Anguilla',
    countryCode: 'AI',
    region: 'South/Latin America',
    flag: '🇦🇮',
  },
  {
    countryNameEn: 'Albania',
    countryCode: 'AL',
    region: 'Europe',
    flag: '🇦🇱',
  },
  {
    countryNameEn: 'Armenia',
    countryCode: 'AM',
    region: 'Europe',
    flag: '🇦🇲',
  },
  {
    countryNameEn: 'Angola',
    countryCode: 'AO',
    region: 'Africa',
    flag: '🇦🇴',
  },
  {
    countryNameEn: 'Antarctica',
    countryCode: 'AQ',
    region: 'Asia & Pacific',
    flag: '🇦🇶',
  },
  {
    countryNameEn: 'Argentina',
    countryCode: 'AR',
    region: 'South/Latin America',
    flag: '🇦🇷',
  },
  {
    countryNameEn: 'American Samoa',
    countryCode: 'AS',
    region: 'Asia & Pacific',
    flag: '🇦🇸',
  },
  {
    countryNameEn: 'Austria',
    countryCode: 'AT',
    region: 'Europe',
    flag: '🇦🇹',
  },
  {
    countryNameEn: 'Australia',
    countryCode: 'AU',
    region: 'Asia & Pacific',
    flag: '🇦🇺',
  },
  {
    countryNameEn: 'Aruba',
    countryCode: 'AW',
    region: 'South/Latin America',
    flag: '🇦🇼',
  },
  {
    countryNameEn: 'Åland Islands',
    countryCode: 'AX',
    region: 'Europe',
    flag: '🇦🇽',
  },
  {
    countryNameEn: 'Azerbaijan',
    countryCode: 'AZ',
    region: 'Asia & Pacific',
    flag: '🇦🇿',
  },
  {
    countryNameEn: 'Bosnia and Herzegovina',
    countryCode: 'BA',
    region: 'Europe',
    flag: '🇧🇦',
  },
  {
    countryNameEn: 'Barbados',
    countryCode: 'BB',
    region: 'South/Latin America',
    flag: '🇧🇧',
  },
  {
    countryNameEn: 'Bangladesh',
    countryCode: 'BD',
    region: 'Asia & Pacific',
    flag: '🇧🇩',
  },
  {
    countryNameEn: 'Belgium',
    countryCode: 'BE',
    region: 'Europe',
    flag: '🇧🇪',
  },
  {
    countryNameEn: 'Burkina Faso',
    countryCode: 'BF',
    region: 'Africa',
    flag: '🇧🇫',
  },
  {
    countryNameEn: 'Bulgaria',
    countryCode: 'BG',
    region: 'Europe',
    flag: '🇧🇬',
  },
  {
    countryNameEn: 'Bahrain',
    countryCode: 'BH',
    region: 'Arab States',
    flag: '🇧🇭',
  },
  {
    countryNameEn: 'Burundi',
    countryCode: 'BI',
    region: 'Africa',
    flag: '🇧🇮',
  },
  {
    countryNameEn: 'Benin',
    countryCode: 'BJ',
    region: 'Africa',
    flag: '🇧🇯',
  },
  {
    countryNameEn: 'Saint Barthélemy',
    countryCode: 'BL',
    region: 'South/Latin America',
    flag: '🇧🇱',
  },
  {
    countryNameEn: 'Bermuda',
    countryCode: 'BM',
    region: 'North America',
    flag: '🇧🇲',
  },
  {
    countryNameEn: 'Brunei Darussalam',
    countryCode: 'BN',
    region: 'Asia & Pacific',
    flag: '🇧🇳',
  },
  {
    countryNameEn: 'Bolivia (Plurinational State of)',
    countryCode: 'BO',
    region: 'South/Latin America',
    flag: '🇧🇴',
  },
  {
    countryNameEn: 'Bonaire, Sint Eustatius and Saba',
    countryCode: 'BQ',
    region: 'Unknown',
    flag: '🇧🇶',
  },
  {
    countryNameEn: 'Brazil',
    countryCode: 'BR',
    region: 'South/Latin America',
    flag: '🇧🇷',
  },
  {
    countryNameEn: 'Bhutan',
    countryCode: 'BT',
    region: 'Asia & Pacific',
    flag: '🇧🇹',
  },
  {
    countryNameEn: 'Bouvet Island',
    countryCode: 'BV',
    region: 'South/Latin America',
    flag: '🇧🇻',
  },
  {
    countryNameEn: 'Botswana',
    countryCode: 'BW',
    region: 'Africa',
    flag: '🇧🇼',
  },
  {
    countryNameEn: 'Belarus',
    countryCode: 'BY',
    region: 'Europe',
    flag: '🇧🇾',
  },
  {
    countryNameEn: 'Belize',
    countryCode: 'BZ',
    region: 'South/Latin America',
    flag: '🇧🇿',
  },
  {
    countryNameEn: 'Canada',
    countryCode: 'CA',
    region: 'North America',
    flag: '🇨🇦',
  },
  {
    countryNameEn: 'Switzerland',
    countryCode: 'CH',
    region: 'Europe',
    flag: '🇨🇭',
  },
  {
    countryNameEn: "Côte d'Ivoire",
    countryCode: 'CI',
    region: 'Africa',
    flag: '🇨🇮',
  },
  {
    countryNameEn: 'Chile',
    countryCode: 'CL',
    region: 'South/Latin America',
    flag: '🇨🇱',
  },
  {
    countryNameEn: 'Cameroon',
    countryCode: 'CM',
    region: 'Africa',
    flag: '🇨🇲',
  },
  {
    countryNameEn: 'China',
    countryCode: 'CN',
    region: 'Asia & Pacific',
    flag: '🇨🇳',
  },
  {
    countryNameEn: 'Colombia',
    countryCode: 'CO',
    region: 'South/Latin America',
    flag: '🇨🇴',
  },
  {
    countryNameEn: 'Costa Rica',
    countryCode: 'CR',
    region: 'South/Latin America',
    flag: '🇨🇷',
  },
  {
    countryNameEn: 'Cuba',
    countryCode: 'CU',
    region: 'South/Latin America',
    flag: '🇨🇺',
  },
  {
    countryNameEn: 'Cabo Verde',
    countryCode: 'CV',
    region: 'Africa',
    flag: '🇨🇻',
  },
  {
    countryNameEn: 'Curaçao',
    countryCode: 'CW',
    region: 'Unknown',
    flag: '🇨🇼',
  },
  {
    countryNameEn: 'Christmas Island',
    countryCode: 'CX',
    region: 'Asia & Pacific',
    flag: '🇨🇽',
  },
  {
    countryNameEn: 'Cyprus',
    countryCode: 'CY',
    region: 'Europe',
    flag: '🇨🇾',
  },
  {
    countryNameEn: 'Germany',
    countryCode: 'DE',
    region: 'Europe',
    flag: '🇩🇪',
  },
  {
    countryNameEn: 'Djibouti',
    countryCode: 'DJ',
    region: 'Arab States',
    flag: '🇩🇯',
  },
  {
    countryNameEn: 'Denmark',
    countryCode: 'DK',
    region: 'Europe',
    flag: '🇩🇰',
  },
  {
    countryNameEn: 'Dominica',
    countryCode: 'DM',
    region: 'South/Latin America',
    flag: '🇩🇲',
  },
  {
    countryNameEn: 'Algeria',
    countryCode: 'DZ',
    region: 'Arab States',
    flag: '🇩🇿',
  },
  {
    countryNameEn: 'Ecuador',
    countryCode: 'EC',
    region: 'South/Latin America',
    flag: '🇪🇨',
  },
  {
    countryNameEn: 'Estonia',
    countryCode: 'EE',
    region: 'Europe',
    flag: '🇪🇪',
  },
  {
    countryNameEn: 'Egypt',
    countryCode: 'EG',
    region: 'Arab States',
    flag: '🇪🇬',
  },
  {
    countryNameEn: 'Western Sahara',
    countryCode: 'EH',
    region: 'Africa',
    flag: '🇪🇭',
  },
  {
    countryNameEn: 'Eritrea',
    countryCode: 'ER',
    region: 'Africa',
    flag: '🇪🇷',
  },
  {
    countryNameEn: 'Spain',
    countryCode: 'ES',
    region: 'Europe',
    flag: '🇪🇸',
  },
  {
    countryNameEn: 'Ethiopia',
    countryCode: 'ET',
    region: 'Africa',
    flag: '🇪🇹',
  },
  {
    countryNameEn: 'Finland',
    countryCode: 'FI',
    region: 'Europe',
    flag: '🇫🇮',
  },
  {
    countryNameEn: 'Fiji',
    countryCode: 'FJ',
    region: 'Asia & Pacific',
    flag: '🇫🇯',
  },
  {
    countryNameEn: 'Micronesia (Federated States of)',
    countryCode: 'FM',
    region: 'Asia & Pacific',
    flag: '🇫🇲',
  },
  {
    countryNameEn: 'France',
    countryCode: 'FR',
    region: 'Europe',
    flag: '🇫🇷',
  },
  {
    countryNameEn: 'Gabon',
    countryCode: 'GA',
    region: 'Africa',
    flag: '🇬🇦',
  },
  {
    countryNameEn: 'Grenada',
    countryCode: 'GD',
    region: 'South/Latin America',
    flag: '🇬🇩',
  },
  {
    countryNameEn: 'Georgia',
    countryCode: 'GE',
    region: 'Europe',
    flag: '🇬🇪',
  },
  {
    countryNameEn: 'French Guiana',
    countryCode: 'GF',
    region: 'South/Latin America',
    flag: '🇬🇫',
  },
  {
    countryNameEn: 'Guernsey',
    countryCode: 'GG',
    region: 'Europe',
    flag: '🇬🇬',
  },
  {
    countryNameEn: 'Ghana',
    countryCode: 'GH',
    region: 'Africa',
    flag: '🇬🇭',
  },
  {
    countryNameEn: 'Gibraltar',
    countryCode: 'GI',
    region: 'Europe',
    flag: '🇬🇮',
  },
  {
    countryNameEn: 'Greenland',
    countryCode: 'GL',
    region: 'Europe',
    flag: '🇬🇱',
  },
  {
    countryNameEn: 'Guinea',
    countryCode: 'GN',
    region: 'Africa',
    flag: '🇬🇳',
  },
  {
    countryNameEn: 'Guadeloupe',
    countryCode: 'GP',
    region: 'South/Latin America',
    flag: '🇬🇵',
  },
  {
    countryNameEn: 'Equatorial Guinea',
    countryCode: 'GQ',
    region: 'Africa',
    flag: '🇬🇶',
  },
  {
    countryNameEn: 'Greece',
    countryCode: 'GR',
    region: 'Europe',
    flag: '🇬🇷',
  },
  {
    countryNameEn: 'South Georgia and the South Sandwich Islands',
    countryCode: 'GS',
    region: 'South/Latin America',
    flag: '🇬🇸',
  },
  {
    countryNameEn: 'Guatemala',
    countryCode: 'GT',
    region: 'South/Latin America',
    flag: '🇬🇹',
  },
  {
    countryNameEn: 'Guam',
    countryCode: 'GU',
    region: 'Asia & Pacific',
    flag: '🇬🇺',
  },
  {
    countryNameEn: 'Guinea-Bissau',
    countryCode: 'GW',
    region: 'Africa',
    flag: '🇬🇼',
  },
  {
    countryNameEn: 'Guyana',
    countryCode: 'GY',
    region: 'South/Latin America',
    flag: '🇬🇾',
  },
  {
    countryNameEn: 'Hong Kong',
    countryCode: 'HK',
    region: 'Asia & Pacific',
    flag: '🇭🇰',
  },
  {
    countryNameEn: 'Honduras',
    countryCode: 'HN',
    region: 'South/Latin America',
    flag: '🇭🇳',
  },
  {
    countryNameEn: 'Croatia',
    countryCode: 'HR',
    region: 'Europe',
    flag: '🇭🇷',
  },
  {
    countryNameEn: 'Haiti',
    countryCode: 'HT',
    region: 'South/Latin America',
    flag: '🇭🇹',
  },
  {
    countryNameEn: 'Hungary',
    countryCode: 'HU',
    region: 'Europe',
    flag: '🇭🇺',
  },
  {
    countryNameEn: 'Indonesia',
    countryCode: 'ID',
    region: 'Asia & Pacific',
    flag: '🇮🇩',
  },
  {
    countryNameEn: 'Ireland',
    countryCode: 'IE',
    region: 'Europe',
    flag: '🇮🇪',
  },
  {
    countryNameEn: 'Israel',
    countryCode: 'IL',
    region: 'Europe',
    flag: '🇮🇱',
  },
  {
    countryNameEn: 'Isle of Man',
    countryCode: 'IM',
    region: 'Europe',
    flag: '🇮🇲',
  },
  {
    countryNameEn: 'India',
    countryCode: 'IN',
    region: 'Asia & Pacific',
    flag: '🇮🇳',
  },
  {
    countryNameEn: 'British Indian Ocean Territories',
    countryCode: 'IO',
    region: 'Indian Ocean',
    flag: '🇮🇴',
  },
  {
    countryNameEn: 'Iraq',
    countryCode: 'IQ',
    region: 'Arab States',
    flag: '🇮🇶',
  },
  {
    countryNameEn: 'Iran (Islamic Republic of)',
    countryCode: 'IR',
    region: 'Asia & Pacific',
    flag: '🇮🇷',
  },
  {
    countryNameEn: 'Iceland',
    countryCode: 'IS',
    region: 'Europe',
    flag: '🇮🇸',
  },
  {
    countryNameEn: 'Italy',
    countryCode: 'IT',
    region: 'Europe',
    flag: '🇮🇹',
  },
  {
    countryNameEn: 'Jersey',
    countryCode: 'JE',
    region: 'Europe',
    flag: '🇯🇪',
  },
  {
    countryNameEn: 'Jamaica',
    countryCode: 'JM',
    region: 'South/Latin America',
    flag: '🇯🇲',
  },
  {
    countryNameEn: 'Jordan',
    countryCode: 'JO',
    region: 'Arab States',
    flag: '🇯🇴',
  },
  {
    countryNameEn: 'Japan',
    countryCode: 'JP',
    region: 'Asia & Pacific',
    flag: '🇯🇵',
  },
  {
    countryNameEn: 'Kenya',
    countryCode: 'KE',
    region: 'Africa',
    flag: '🇰🇪',
  },
  {
    countryNameEn: 'Kyrgyzstan',
    countryCode: 'KG',
    region: 'Asia & Pacific',
    flag: '🇰🇬',
  },
  {
    countryNameEn: 'Cambodia',
    countryCode: 'KH',
    region: 'Asia & Pacific',
    flag: '🇰🇭',
  },
  {
    countryNameEn: 'North Korea',
    countryCode: 'KP',
    region: 'Asia',
    flag: '🇰🇵',
  },
  {
    countryNameEn: 'South Korea',
    countryCode: 'KR',
    region: 'Asia',
    flag: '🇰🇷',
  },
  {
    countryNameEn: 'Kiribati',
    countryCode: 'KI',
    region: 'Asia & Pacific',
    flag: '🇰🇮',
  },
  {
    countryNameEn: 'Saint Kitts and Nevis',
    countryCode: 'KN',
    region: 'South/Latin America',
    flag: '🇰🇳',
  },
  {
    countryNameEn: 'Kuwait',
    countryCode: 'KW',
    region: 'Arab States',
    flag: '🇰🇼',
  },
  {
    countryNameEn: 'Kazakhstan',
    countryCode: 'KZ',
    region: 'Asia & Pacific',
    flag: '🇰🇿',
  },
  {
    countryNameEn: 'Lebanon',
    countryCode: 'LB',
    region: 'Arab States',
    flag: '🇱🇧',
  },
  {
    countryNameEn: 'Saint Lucia',
    countryCode: 'LC',
    region: 'South/Latin America',
    flag: '🇱🇨',
  },
  {
    countryNameEn: 'Liechtenstein',
    countryCode: 'LI',
    region: 'Europe',
    flag: '🇱🇮',
  },
  {
    countryNameEn: 'Sri Lanka',
    countryCode: 'LK',
    region: 'Asia & Pacific',
    flag: '🇱🇰',
  },
  {
    countryNameEn: 'Liberia',
    countryCode: 'LR',
    region: 'Africa',
    flag: '🇱🇷',
  },
  {
    countryNameEn: 'Lesotho',
    countryCode: 'LS',
    region: 'Africa',
    flag: '🇱🇸',
  },
  {
    countryNameEn: 'Lithuania',
    countryCode: 'LT',
    region: 'Europe',
    flag: '🇱🇹',
  },
  {
    countryNameEn: 'Luxembourg',
    countryCode: 'LU',
    region: 'Europe',
    flag: '🇱🇺',
  },
  {
    countryNameEn: 'Latvia',
    countryCode: 'LV',
    region: 'Europe',
    flag: '🇱🇻',
  },
  {
    countryNameEn: 'Libya',
    countryCode: 'LY',
    region: 'Arab States',
    flag: '🇱🇾',
  },
  {
    countryNameEn: 'Morocco',
    countryCode: 'MA',
    region: 'Arab States',
    flag: '🇲🇦',
  },
  {
    countryNameEn: 'Monaco',
    countryCode: 'MC',
    region: 'Europe',
    flag: '🇲🇨',
  },
  {
    countryNameEn: 'Montenegro',
    countryCode: 'ME',
    region: 'Europe',
    flag: '🇲🇪',
  },
  {
    countryNameEn: 'Saint Martin (French part)',
    countryCode: 'MF',
    region: 'South/Latin America',
    flag: '🇲🇫',
  },
  {
    countryNameEn: 'Madagascar',
    countryCode: 'MG',
    region: 'Africa',
    flag: '🇲🇬',
  },
  {
    countryNameEn: 'Mali',
    countryCode: 'ML',
    region: 'Africa',
    flag: '🇲🇱',
  },
  {
    countryNameEn: 'Myanmar',
    countryCode: 'MM',
    region: 'Asia & Pacific',
    flag: '🇲🇲',
  },
  {
    countryNameEn: 'Mongolia',
    countryCode: 'MN',
    region: 'Asia & Pacific',
    flag: '🇲🇳',
  },
  {
    countryNameEn: 'Macao',
    countryCode: 'MO',
    region: 'Asia & Pacific',
    flag: '🇲🇴',
  },
  {
    countryNameEn: 'Martinique',
    countryCode: 'MQ',
    region: 'South/Latin America',
    flag: '🇲🇶',
  },
  {
    countryNameEn: 'Mauritania',
    countryCode: 'MR',
    region: 'Arab States',
    flag: '🇲🇷',
  },
  {
    countryNameEn: 'Montserrat',
    countryCode: 'MS',
    region: 'South/Latin America',
    flag: '🇲🇸',
  },
  {
    countryNameEn: 'Malta',
    countryCode: 'MT',
    region: 'Europe',
    flag: '🇲🇹',
  },
  {
    countryNameEn: 'Mauritius',
    countryCode: 'MU',
    region: 'Africa',
    flag: '🇲🇺',
  },
  {
    countryNameEn: 'Maldives',
    countryCode: 'MV',
    region: 'Asia & Pacific',
    flag: '🇲🇻',
  },
  {
    countryNameEn: 'Malawi',
    countryCode: 'MW',
    region: 'Africa',
    flag: '🇲🇼',
  },
  {
    countryNameEn: 'Mexico',
    countryCode: 'MX',
    region: 'South/Latin America',
    flag: '🇲🇽',
  },
  {
    countryNameEn: 'Malaysia',
    countryCode: 'MY',
    region: 'Asia & Pacific',
    flag: '🇲🇾',
  },
  {
    countryNameEn: 'Mozambique',
    countryCode: 'MZ',
    region: 'Africa',
    flag: '🇲🇿',
  },
  {
    countryNameEn: 'Namibia',
    countryCode: 'NA',
    region: 'Africa',
    flag: '🇳🇦',
  },
  {
    countryNameEn: 'New Caledonia',
    countryCode: 'NC',
    region: 'Asia & Pacific',
    flag: '🇳🇨',
  },
  {
    countryNameEn: 'Norfolk Island',
    countryCode: 'NF',
    region: 'Asia & Pacific',
    flag: '🇳🇫',
  },
  {
    countryNameEn: 'Nigeria',
    countryCode: 'NG',
    region: 'Africa',
    flag: '🇳🇬',
  },
  {
    countryNameEn: 'Nicaragua',
    countryCode: 'NI',
    region: 'South/Latin America',
    flag: '🇳🇮',
  },
  {
    countryNameEn: 'Norway',
    countryCode: 'NO',
    region: 'Europe',
    flag: '🇳🇴',
  },
  {
    countryNameEn: 'Nepal',
    countryCode: 'NP',
    region: 'Asia & Pacific',
    flag: '🇳🇵',
  },
  {
    countryNameEn: 'Nauru',
    countryCode: 'NR',
    region: 'Asia & Pacific',
    flag: '🇳🇷',
  },
  {
    countryNameEn: 'Niue',
    countryCode: 'NU',
    region: 'Asia & Pacific',
    flag: '🇳🇺',
  },
  {
    countryNameEn: 'New Zealand',
    countryCode: 'NZ',
    region: 'Asia & Pacific',
    flag: '🇳🇿',
  },
  {
    countryNameEn: 'Oman',
    countryCode: 'OM',
    region: 'Arab States',
    flag: '🇴🇲',
  },
  {
    countryNameEn: 'Panama',
    countryCode: 'PA',
    region: 'South/Latin America',
    flag: '🇵🇦',
  },
  {
    countryNameEn: 'Peru',
    countryCode: 'PE',
    region: 'South/Latin America',
    flag: '🇵🇪',
  },
  {
    countryNameEn: 'French Polynesia',
    countryCode: 'PF',
    region: 'Asia & Pacific',
    flag: '🇵🇫',
  },
  {
    countryNameEn: 'Papua New Guinea',
    countryCode: 'PG',
    region: 'Asia & Pacific',
    flag: '🇵🇬',
  },
  {
    countryNameEn: 'Pakistan',
    countryCode: 'PK',
    region: 'Asia & Pacific',
    flag: '🇵🇰',
  },
  {
    countryNameEn: 'Poland',
    countryCode: 'PL',
    region: 'Europe',
    flag: '🇵🇱',
  },
  {
    countryNameEn: 'Saint Pierre and Miquelon',
    countryCode: 'PM',
    region: 'North America',
    flag: '🇵🇲',
  },
  {
    countryNameEn: 'Pitcairn',
    countryCode: 'PN',
    region: 'Asia & Pacific',
    flag: '🇵🇳',
  },
  {
    countryNameEn: 'Puerto Rico',
    countryCode: 'PR',
    region: 'South/Latin America',
    flag: '🇵🇷',
  },
  {
    countryNameEn: 'Palestine, State of',
    countryCode: 'PS',
    region: 'Arab States',
    flag: '🇵🇸',
  },
  {
    countryNameEn: 'Portugal',
    countryCode: 'PT',
    region: 'Europe',
    flag: '🇵🇹',
  },
  {
    countryNameEn: 'Palau',
    countryCode: 'PW',
    region: 'Asia & Pacific',
    flag: '🇵🇼',
  },
  {
    countryNameEn: 'Paraguay',
    countryCode: 'PY',
    region: 'South/Latin America',
    flag: '🇵🇾',
  },
  {
    countryNameEn: 'Qatar',
    countryCode: 'QA',
    region: 'Arab States',
    flag: '🇶🇦',
  },
  {
    countryNameEn: 'Réunion',
    countryCode: 'RE',
    region: 'Asia & Pacific',
    flag: '🇷🇪',
  },
  {
    countryNameEn: 'Romania',
    countryCode: 'RO',
    region: 'Europe',
    flag: '🇷🇴',
  },
  {
    countryNameEn: 'Serbia',
    countryCode: 'RS',
    region: 'Europe',
    flag: '🇷🇸',
  },
  {
    countryNameEn: 'Russia',
    countryCode: 'RU',
    region: 'Europe',
    flag: '🇷🇺',
  },
  {
    countryNameEn: 'Rwanda',
    countryCode: 'RW',
    region: 'Africa',
    flag: '🇷🇼',
  },
  {
    countryNameEn: 'Saudi Arabia',
    countryCode: 'SA',
    region: 'Arab States',
    flag: '🇸🇦',
  },
  {
    countryNameEn: 'Solomon Islands',
    countryCode: 'SB',
    region: 'Asia & Pacific',
    flag: '🇸🇧',
  },
  {
    countryNameEn: 'Seychelles',
    countryCode: 'SC',
    region: 'Africa',
    flag: '🇸🇨',
  },
  {
    countryNameEn: 'Sweden',
    countryCode: 'SE',
    region: 'Europe',
    flag: '🇸🇪',
  },
  {
    countryNameEn: 'Singapore',
    countryCode: 'SG',
    region: 'Asia & Pacific',
    flag: '🇸🇬',
  },
  {
    countryNameEn: 'Saint Helena, Ascension and Tristan da Cunha',
    countryCode: 'SH',
    region: 'Africa',
    flag: '🇸🇭',
  },
  {
    countryNameEn: 'Slovenia',
    countryCode: 'SI',
    region: 'Europe',
    flag: '🇸🇮',
  },
  {
    countryNameEn: 'Svalbard and Jan Mayen',
    countryCode: 'SJ',
    region: 'Europe',
    flag: '🇸🇯',
  },
  {
    countryNameEn: 'Slovakia',
    countryCode: 'SK',
    region: 'Europe',
    flag: '🇸🇰',
  },
  {
    countryNameEn: 'Sierra Leone',
    countryCode: 'SL',
    region: 'Africa',
    flag: '🇸🇱',
  },
  {
    countryNameEn: 'Republic of San Marino',
    countryCode: 'SM',
    region: 'Europe',
    flag: '🇸🇲',
  },
  {
    countryNameEn: 'Senegal',
    countryCode: 'SN',
    region: 'Africa',
    flag: '🇸🇳',
  },
  {
    countryNameEn: 'Somalia',
    countryCode: 'SO',
    region: 'Arab States',
    flag: '🇸🇴',
  },
  {
    countryNameEn: 'Suriname',
    countryCode: 'SR',
    region: 'South/Latin America',
    flag: '🇸🇷',
  },
  {
    countryNameEn: 'South Sudan',
    countryCode: 'SS',
    region: 'Africa',
    flag: '🇸🇸',
  },
  {
    countryNameEn: 'Sao Tome and Principe',
    countryCode: 'ST',
    region: 'Africa',
    flag: '🇸🇹',
  },
  {
    countryNameEn: 'El Salvador',
    countryCode: 'SV',
    region: 'South/Latin America',
    flag: '🇸🇻',
  },
  {
    countryNameEn: 'Sint Maarten (Dutch part)',
    countryCode: 'SX',
    region: 'Unknown',
    flag: '🇸🇽',
  },
  {
    countryNameEn: 'Syrian Arab Republic',
    countryCode: 'SY',
    region: 'Asia & Pacific',
    flag: '🇸🇾',
  },
  {
    countryNameEn: 'Chad',
    countryCode: 'TD',
    region: 'Africa',
    flag: '🇹🇩',
  },
  {
    countryNameEn: 'Togo',
    countryCode: 'TG',
    region: 'Africa',
    flag: '🇹🇬',
  },
  {
    countryNameEn: 'Thailand',
    countryCode: 'TH',
    region: 'Asia & Pacific',
    flag: '🇹🇭',
  },
  {
    countryNameEn: 'Tajikistan',
    countryCode: 'TJ',
    region: 'Asia & Pacific',
    flag: '🇹🇯',
  },
  {
    countryNameEn: 'Tokelau',
    countryCode: 'TK',
    region: 'Asia & Pacific',
    flag: '🇹🇰',
  },
  {
    countryNameEn: 'Timor-Leste',
    countryCode: 'TL',
    region: 'Asia & Pacific',
    flag: '🇹🇱',
  },
  {
    countryNameEn: 'Turkmenistan',
    countryCode: 'TM',
    region: 'Asia & Pacific',
    flag: '🇹🇲',
  },
  {
    countryNameEn: 'Tunisia',
    countryCode: 'TN',
    region: 'Arab States',
    flag: '🇹🇳',
  },
  {
    countryNameEn: 'Tonga',
    countryCode: 'TO',
    region: 'Asia & Pacific',
    flag: '🇹🇴',
  },
  {
    countryNameEn: 'Turkey',
    countryCode: 'TR',
    region: 'Europe',
    flag: '🇹🇷',
  },
  {
    countryNameEn: 'Trinidad and Tobago',
    countryCode: 'TT',
    region: 'South/Latin America',
    flag: '🇹🇹',
  },
  {
    countryNameEn: 'Tuvalu',
    countryCode: 'TV',
    region: 'Asia & Pacific',
    flag: '🇹🇻',
  },
  {
    countryNameEn: 'United Republic of Tanzania',
    countryCode: 'TZ',
    region: 'Africa',
    flag: '🇹🇿',
  },
  {
    countryNameEn: 'Ukraine',
    countryCode: 'UA',
    region: 'Europe',
    flag: '🇺🇦',
  },
  {
    countryNameEn: 'Uganda',
    countryCode: 'UG',
    region: 'Africa',
    flag: '🇺🇬',
  },
  {
    countryNameEn: 'United States of America',
    countryCode: 'US',
    region: 'North America',
    flag: '🇺🇸',
  },
  {
    countryNameEn: 'Uruguay',
    countryCode: 'UY',
    region: 'South/Latin America',
    flag: '🇺🇾',
  },
  {
    countryNameEn: 'Uzbekistan',
    countryCode: 'UZ',
    region: 'Asia & Pacific',
    flag: '🇺🇿',
  },
  {
    countryNameEn: 'Saint Vincent and the Grenadines',
    countryCode: 'VC',
    region: 'South/Latin America',
    flag: '🇻🇨',
  },
  {
    countryNameEn: 'Venezuela (Bolivarian Republic of)',
    countryCode: 'VE',
    region: 'South/Latin America',
    flag: '🇻🇪',
  },
  {
    countryNameEn: 'Virgin Islands (British)',
    countryCode: 'VG',
    region: 'South/Latin America',
    flag: '🇻🇬',
  },
  {
    countryNameEn: 'Virgin Islands (U.S.)',
    countryCode: 'VI',
    region: 'South/Latin America',
    flag: '🇻🇮',
  },
  {
    countryNameEn: 'Vietnam',
    countryCode: 'VN',
    region: 'Asia & Pacific',
    flag: '🇻🇳',
  },
  {
    countryNameEn: 'Vanuatu',
    countryCode: 'VU',
    region: 'Asia & Pacific',
    flag: '🇻🇺',
  },
  {
    countryNameEn: 'Wallis and Futuna',
    countryCode: 'WF',
    region: 'Asia & Pacific',
    flag: '🇼🇫',
  },
  {
    countryNameEn: 'Samoa',
    countryCode: 'WS',
    region: 'Asia & Pacific',
    flag: '🇼🇸',
  },
  {
    countryNameEn: 'Yemen',
    countryCode: 'YE',
    region: 'Arab States',
    flag: '🇾🇪',
  },
  {
    countryNameEn: 'Mayotte',
    countryCode: 'YT',
    region: 'Africa',
    flag: '🇾🇹',
  },
  {
    countryNameEn: 'South Africa',
    countryCode: 'ZA',
    region: 'Africa',
    flag: '🇿🇦',
  },
  {
    countryNameEn: 'Zambia',
    countryCode: 'ZM',
    region: 'Africa',
    flag: '🇿🇲',
  },
  {
    countryNameEn: 'Zimbabwe',
    countryCode: 'ZW',
    region: 'Africa',
    flag: '🇿🇼',
  },
  {
    countryNameEn: 'Eswatini',
    countryCode: 'SZ',
    region: 'Africa',
    flag: '🇸🇿',
  },
  {
    countryNameEn: 'North Macedonia',
    countryCode: 'MK',
    region: 'Europe',
    flag: '🇲🇰',
  },
  {
    countryNameEn: 'Philippines',
    countryCode: 'PH',
    region: 'Asia & Pacific',
    flag: '🇵🇭',
  },
  {
    countryNameEn: 'Netherlands',
    countryCode: 'NL',
    region: 'Europe',
    flag: '🇳🇱',
  },
  {
    countryNameEn: 'United Arab Emirates',
    countryCode: 'AE',
    region: 'Arab States',
    flag: '🇦🇪',
  },
  {
    countryNameEn: 'Republic of Moldova',
    countryCode: 'MD',
    region: 'Europe',
    flag: '🇲🇩',
  },
  {
    countryNameEn: 'Gambia',
    countryCode: 'GM',
    region: 'Africa',
    flag: '🇬🇲',
  },
  {
    countryNameEn: 'Dominican Republic',
    countryCode: 'DO',
    region: 'South/Latin America',
    flag: '🇩🇴',
  },
  {
    countryNameEn: 'Sudan',
    countryCode: 'SD',
    region: 'Arab States',
    flag: '🇸🇩',
  },
  {
    countryNameEn: "Lao People's Democratic Republic",
    countryCode: 'LA',
    region: 'Asia & Pacific',
    flag: '🇱🇦',
  },
  {
    countryNameEn: 'Taiwan, Province of China',
    countryCode: 'TW',
    region: 'Asia & Pacific',
    flag: '🇹🇼',
  },
  {
    countryNameEn: 'Republic of the Congo',
    countryCode: 'CG',
    region: 'Africa',
    flag: '🇨🇬',
  },
  {
    countryNameEn: 'Czechia',
    countryCode: 'CZ',
    region: 'Europe',
    flag: '🇨🇿',
  },
  {
    countryNameEn: 'United Kingdom',
    countryCode: 'GB',
    region: 'Europe',
    flag: '🇬🇧',
  },
  {
    countryNameEn: 'Niger',
    countryCode: 'NE',
    region: 'Africa',
    flag: '🇳🇪',
  },
  {
    countryNameEn: 'Democratic Republic of the Congo',
    countryCode: 'CD',
    region: 'Africa',
    flag: '🇨🇩',
  },
  {
    countryNameEn: 'Commonwealth of The Bahamas',
    countryCode: 'BS',
    region: 'Caribbean',
    flag: '🇧🇸',
  },
  {
    countryNameEn: 'Cocos (Keeling) Islands',
    countryCode: 'CC',
    region: 'Australia',
    flag: '🇨🇨',
  },
  {
    countryNameEn: 'Central African Republic',
    countryCode: 'CF',
    region: 'Africa',
    flag: '🇨🇫',
  },
  {
    countryNameEn: 'Cook Islands',
    countryCode: 'CK',
    region: 'South Pacific Ocean',
    flag: '🇨🇰',
  },
  {
    countryNameEn: 'Falkland Islands',
    countryCode: 'FK',
    region: 'South Atlantic Ocean',
    flag: '🇫🇰',
  },
  {
    countryNameEn: 'Faroe Islands',
    countryCode: 'FO',
    region: 'Europe',
    flag: '🇫🇴',
  },
  {
    countryNameEn: 'Territory of Heard Island and McDonald Islands',
    countryCode: 'HM',
    region: 'Indian Ocean',
    flag: '🇭🇲',
  },
  {
    countryNameEn: 'British Indian Ocean Territory',
    countryCode: 'IO',
    region: 'Indian Ocean',
    flag: '🇮🇴',
  },
  {
    countryNameEn: 'Comoros',
    countryCode: 'KM',
    region: 'Indian Ocean',
    flag: '🇰🇲',
  },
  {
    countryNameEn: 'Cayman Islands',
    countryCode: 'KY',
    region: 'Caribbean Sea',
    flag: '🇰🇾',
  },
  {
    countryNameEn: 'Republic of the Marshall Islands',
    countryCode: 'MH',
    region: 'Pacific Ocean',
    flag: '🇲🇭',
  },
  {
    countryNameEn: 'Commonwealth of the Northern Mariana Islands',
    countryCode: 'MP',
    region: 'Pacific Ocean',
    flag: '🇲🇵',
  },
  {
    countryNameEn: 'Turks and Caicos Islands',
    countryCode: 'TC',
    region: 'Atlantic Ocean',
    flag: '🇹🇨',
  },
  {
    countryNameEn: 'French Southern and Antarctic Lands',
    countryCode: 'TF',
    region: 'Indian Ocean',
    flag: '🇹🇫',
  },
  {
    countryNameEn: 'United States Minor Outlying Islands',
    countryCode: 'UM',
    region: 'Pacific Ocean',
    flag: '🇺🇲',
  },
  {
    countryNameEn: 'Holy See',
    countryCode: 'VA',
    region: 'Europe',
    flag: '🇻🇦',
  },
  {
    countryNameEn: 'Republic of Kosovo',
    countryCode: 'XK',
    flag: '🇽🇰',
  },
  {
    countryNameEn: 'Netherlands Antilles',
    countryCode: 'AN',
    flag: '🇧🇶',
  },
];
